# Generated by Django 4.2 on 2023-04-16 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
                ('bin_ip', models.CharField(max_length=12, unique=True)),
                ('moisture', models.IntegerField()),
                ('filled', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anchor')),
            ],
        ),
    ]
