# Generated by Django 4.2 on 2023-04-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anchor_bin_id_alter_bin_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='bin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bin'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anchor'),
        ),
    ]
